version: "3.8"

services:
    database:
        image: 'mysql:latest'
        container_name: lbc_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: lbc_api
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306'
        networks:
            - lbc_api

    phpmyadmin:
        image: phpmyadmin
        container_name: lbc_phpmyadmin
        depends_on:
            - database
        ports:
            - "8080:80"
        environment:
            PMA_HOST: database
        networks:
            lbc_api:

    web:
        build: .docker/php
        container_name: lbc_api_web
        ports:
            - "8741:80"
        volumes:
            - .docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www/lbc-api
        restart: always
        networks:
            lbc_api:

networks:
    lbc_api:
volumes:
    db-data:
