version: "3.8"

services:
    database:
        image: 'mysql:8.0.28'
        container_name: lbc_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
        networks:
            dev:

    phpmyadmin:
        image: phpmyadmin
        container_name: lbc_phpmyadmin
        depends_on:
            - database
        ports:
            - "8080:80"
        environment:
            PMA_HOST: database
        networks:
            dev:

    web:
        build: .docker/php
        container_name: lbc_api_web
        depends_on:
            - database
        ports:
            - "8741:80"
        volumes:
            - .docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www/lbc-api
        environment:
            DATABASE_URL: mysql://root:@database/lbc_api?serverVersion=8.0.28
            JWT_PASSPHRASE: c463b02d15d77171325e6cd785821828
        restart: always
        networks:
            dev:

networks:
    dev:
volumes:
    db-data:
